Repository jonasyr/gitray, pull requests merged in 2025-05, with the labels that each got.

#26 Build & Run Tutorial README
  README.md
Labels: type:documentation, prio:low

#27 Add repository routes for handling commits and URL validation
  README.md
  apps/backend/src/index.ts
  apps/backend/src/routes/repositoryRoutes.ts
Labels: scope:backend, prio:high

#31 Created API Service api.ts, added axios + Unit Test
  apps/frontend/package.json
  apps/frontend/src/__tests__/api.test.tsx
  apps/frontend/src/services/api.ts
  apps/frontend/vite.config.ts
  pnpm-lock.yaml
Labels: scope:frontend, prio:medium, type:chore

#30 Added Unit Test for gitService & Added Claude.md file
  CLAUDE.md
  apps/backend/__tests__/services/gitService.test.ts
Labels: scope:backend, prio:medium

#33 Integrated SonarQube and optimized CI
  .github/workflows/build.yml
  .github/workflows/ci.yml
  .github/workflows/lint.yml
  .github/workflows/test.yml
  sonar-project.properties
Labels: prio:medium, scope:shared

#51 Updated SonarQube Exclusion Patterns for Accurate Code Coverage
  sonar-project.properties
Labels: prio:medium, type:chore

#52 Removed second exclusion line
  .github/workflows/ci.yml
  sonar-project.properties
Labels: prio:medium, type:chore

#54 Improve Test Coverage for Better SonarQube Metrics
  .gitignore
  apps/backend/__tests__/index.test.ts
  apps/backend/__tests__/middlewares/errorHandler.test.ts
  apps/backend/__tests__/routes/index.test.ts
  apps/backend/__tests__/routes/repositoryRoutes.test.ts
  apps/backend/__tests__/services/gitService.test.ts
  apps/backend/src/index.js
  apps/backend/src/middlewares/errorHandler.js
  apps/backend/src/routes/index.js
  apps/backend/src/routes/repositoryRoutes.js
  apps/backend/src/services/gitService.js
  apps/backend/src/services/gitService.ts
  apps/frontend/src/__tests__/main.test.tsx
  sonar-project.properties
Labels: prio:high, scope:shared

#55 Activity Heatmap Visualization
  .github/workflows/ci.yml
  .husky/pre-commit
  AGENTS.md
  CLAUDE.md
  README.md
  apps/backend/__tests__/aggregateCommits.test.ts
  apps/backend/__tests__/index.test.ts
  apps/backend/__tests__/middlewares/errorHandler.test.ts
  apps/backend/__tests__/routes/commitRoutes.test.ts
  apps/backend/__tests__/routes/index.test.ts
  apps/backend/__tests__/routes/repositoryRoutes.test.ts
  apps/backend/__tests__/services/gitService.test.ts
  apps/backend/package.json
  apps/backend/src/index.ts
  apps/backend/src/routes/commitRoutes.ts
  apps/backend/src/routes/repositoryRoutes.ts
  apps/backend/src/services/gitService.ts
  apps/backend/tsconfig.json
  apps/frontend/__mocks__/ansi-styles.cjs
  apps/frontend/__tests__/App.test.tsx
  apps/frontend/__tests__/components/ActivityHeatmap.test.tsx
  apps/frontend/__tests__/components/CommitList.test.tsx
  apps/frontend/__tests__/main.test.tsx
  apps/frontend/__tests__/pages/MainPage.test.tsx
  apps/frontend/__tests__/services/api.test.tsx
  apps/frontend/__tests__/services/apiExtended.test.tsx
  apps/frontend/__tests__/utils/dateUtils.test.tsx
  apps/frontend/jest.config.cjs
  apps/frontend/package.json
  apps/frontend/src/App.tsx
  apps/frontend/src/__tests__/MainPage.test.tsx
  apps/frontend/src/components/ActivityHeatmap.tsx
  apps/frontend/src/components/CommitList.tsx
  apps/frontend/src/components/RepoInput.tsx
  apps/frontend/src/index.css
  apps/frontend/src/pages/MainPage.tsx
  apps/frontend/src/services/api.ts
  apps/frontend/src/styles/heatmap.css
  apps/frontend/src/types/react-calendar-heatmap.d.ts
  apps/frontend/src/utils/dateUtils.ts
  apps/frontend/tsconfig.app.json
  apps/frontend/tsconfig.json
  apps/frontend/vite.config.ts
  docs/JEST_ESM_CONFIG.md
  docs/JEST_MOCK.md
  docs/JEST_MOCK_SOLUTION.md
  eslint.config.mjs
  jest.config.cjs
  package.json
  packages/shared-types/package.json
  packages/shared-types/src/index.ts
  pnpm-lock.yaml
Labels: type:feature, prio:high, scope:shared

#56 Update sonar exclusions to exclude main.tsx
  sonar-project.properties
Labels: prio:high, type:chore

#61 Fix parsing of commit messages with pipe
  apps/backend/__tests__/services/gitService.test.ts
  apps/backend/src/services/gitService.ts
Labels: codex
